config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [] do
        resources :posts, only: %i[index]
      end

      resources :users, only: [] do
        resources :posts, only: %i[index show new create] do
          resources :comments, only: %i[new create]
          resources :likes, only: %i[new create]
        end
      end

      resources :posts, only: [] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id

  attribute :email, :string
  attribute :username, :string
  attribute :encrypted_password, :string
  has_one_attached :photo

  validates :name, presence: true, allow_blank: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  before_save :generate_api_token

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def update_posts_counter
    update(posts_counter: posts.count)
  end

  def update_comments_counter
    update(comments_counter: comments.count)
  end


  private

  def generate_api_token
    self.api_token = SecureRandom.hex(16)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # Logic for index action
    @users = User.all
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    # Logic for show action
    @user = User.find(params[:id])
    @user.posts_counter = @user.posts.count
  end

end

app/views/users/index.html.erb
<main>
  <section>
    <ul>
      <% @users.each do |user| %>
        <%= link_to user_path(user) do %>
          <li class="card hover">

            <% if user.photo.present? %>
              <%= image_tag(user.photo, class: "user-image border") %>
            <% else %>
              <div class ="user-image border">
                <%= image_tag "avatar.jpeg" %>
              </div>
            <% end %>
            <div class="user-data border">
              <h1><%= user.name %></h1>
              <p class="number-posts">Number of posts: <%= user.posts_counter %></p>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= will_paginate @users %>
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section>
    <div class="card">
      <% if @user.photo.present? %>
        <%= image_tag(@user.photo, class: "user-image border") %>
      <% else %>
        <div class ="user-image border">
          <%= image_tag "avatar.jpeg" %>
        </div>
      <% end %>
      <div class="user-data border">
        <h1><%= @user.name %></h1>
        <p><%= @user.bio %></p>
        <p class="number-posts">Number of posts: <%= @user.posts_counter %></p>
        <div class="right">
          <%= link_to "Add a post", new_user_post_path(@user), class: "btn right" %>
        </div>
      </div>
    </div>
  </section>
  <section class="center">
    <ul>
      <% @user.posts.each do |post| %>
        <%= link_to user_post_path(@user, post) do %>
          <li class="card column hover">
            <h3 class="left"><%= post.title%></h3>
            <h4 class="left"><%= post.text%></h4>
            <div class="right">
              <span>Comments: <%= post.comments_counter %></span>
              <span class="left">Likes: <%= post.likes_counter %> </span>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "btn" %>
  </section>
</main>